(cl:in-package gnss_pkg-msg)
(cl:export '(HEADER-VAL
          HEADER
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          HEADING-VAL
          HEADING
          LONGTITUDE-VAL
          LONGTITUDE
          LATITUDE-VAL
          LATITUDE
          ALTITUDE-VAL
          ALTITUDE
          SPEED2D-VAL
          SPEED2D
          VE-VAL
          VE
          VN-VAL
          VN
          VU-VAL
          VU
          GPSTIME-VAL
          GPSTIME
          POSE_TYPE-VAL
          POSE_TYPE
          INS_STATUS-VAL
          INS_STATUS
          LAT_VART-VAL
          LAT_VART
          LON_VART-VAL
          LON_VART
))